apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
bases:
  - ../../base
resources:
- deployment.yaml
- loki-secret.yaml

commonLabels:
  env: surge
  app: loki

patchesStrategicMerge:
  - patches/loki-secret_patch.yaml
